platform :ios, '7.0'

pod 'SDWebImage'
pod 'VCTransitionsLibrary'
pod 'FMDB'
pod 'CTAssetsPickerController',  '~> 2.8.0'
pod 'MJExtension'
pod 'SCRecorder'
pod 'UIImage-ResizeMagick'
pod 'SZTextView'
pod 'CRNavigationController'
